  window.DADOS_FRETE = {
  "transportadoras": [
    {
  "nome": "Cbirdex",
  "uf": "CE",   
  "valorPorKg": 0.45,
  "valorPorNF": 0.005,
  "taxaColeta": 0,
  "freteMinimo": 60.00,
  "prazos": {
    "Abaiara": 24,
    "Acarape": { "uf": "CE", "prazo": 24 },
    "Acarau": { "uf": "CE", "prazo": 72 },
    "Acopiara": { "uf": "CE", "prazo": 24 },
    "Aiuaba": { "uf": "CE", "prazo": 48 },
    "Alcantaras": { "uf": "CE", "prazo": 72 },
    "Altaneira": { "uf": "CE", "prazo": 48 },
    "Alto Santo": { "uf": "CE", "prazo": 72 },
    "Amontada": { "uf": "CE", "prazo": 72 },
    "Antonina do Norte": { "uf": "CE", "prazo": 48 },
    "Apuiares": { "uf": "CE", "prazo": 48 },
    "Aquiraz": { "uf": "CE", "prazo": 24 },
    "Aracati": { "uf": "CE", "prazo": 24 },
    "Aracoiaba": { "uf": "CE", "prazo": 72 },
    "Ararenda": { "uf": "CE", "prazo": 24 },
    "Araripe": { "uf": "CE", "prazo": 24 },
    "Aratuba": { "uf": "CE", "prazo": 72 },
    "Arneiroz": { "uf": "CE", "prazo": 48 },
    "Assare": { "uf": "CE", "prazo": 24 },
    "Aurora": { "uf": "CE", "prazo": 24 },
    "Baixio": { "uf": "CE", "prazo": 24 },
    "Banabuiu": { "uf": "CE", "prazo": 48 },
    "Barbalha": { "uf": "CE", "prazo": 24 },
    "Barreira": { "uf": "CE", "prazo": 72 },
    "Barro": { "uf": "CE", "prazo": 48 },
    "Barroquinha": { "uf": "CE", "prazo": 72 },
    "Baturite": { "uf": "CE", "prazo": 24 },
    "Beberibe": { "uf": "CE", "prazo": 24 },
    "Bela Cruz": { "uf": "CE", "prazo": 72 },
    "Boa Viagem": { "uf": "CE", "prazo": 48 },
    "Brejo Santo": { "uf": "CE", "prazo": 24 },
    "Camocim": { "uf": "CE", "prazo": 72 },
    "Campos Sales": { "uf": "CE", "prazo": 24 },
    "Caninde": { "uf": "CE", "prazo": 24 },
    "Capistrano": { "uf": "CE", "prazo": 72 },
    "Caridade": { "uf": "CE", "prazo": 72 },
    "Carire": { "uf": "CE", "prazo": 72 },
    "Caririaçu": { "uf": "CE", "prazo": 24 },
    "Carius": { "uf": "CE", "prazo": 48 },
    "Carnaubal": { "uf": "CE", "prazo": 72 },
    "Cascavel": { "uf": "CE", "prazo": 24 },
    "Catarina": { "uf": "CE", "prazo": 48 },
    "Catunda": { "uf": "CE", "prazo": 24 },
    "Caucaia": { "uf": "CE", "prazo": 24 },
    "Cedro": { "uf": "CE", "prazo": 48 },
    "Chaval": { "uf": "CE", "prazo": 72 },
    "Choro": { "uf": "CE", "prazo": 48 },
    "Chorozinho": { "uf": "CE", "prazo": 72 },
    "Coreau": { "uf": "CE", "prazo": 72 },
    "Crateus": { "uf": "CE", "prazo": 24 },
    "Crato": { "uf": "CE", "prazo": 24 },
    "Croata": { "uf": "CE", "prazo": 24 },
    "Cruz": { "uf": "CE", "prazo": 72 },
    "Deputado Irapuan Pinheiro": { "uf": "CE", "prazo": 48 },
    "Erere": { "uf": "CE", "prazo": 72 },
    "Eusebio": { "uf": "CE", "prazo": 24 },
    "Farias Brito": { "uf": "CE", "prazo": 24 },
    "Forquilha": { "uf": "CE", "prazo": 48 },
    "Fortim": { "uf": "CE", "prazo": 48 },
    "Frecheirinha": { "uf": "CE", "prazo": 24 },
    "General Sampaio": { "uf": "CE", "prazo": 48 },
    "Graça": { "uf": "CE", "prazo": 72 },
    "Granja": { "uf": "CE", "prazo": 72 },
    "Granjeiro": { "uf": "CE", "prazo": 72 },
    "Groairas": { "uf": "CE", "prazo": 72 },
    "Guaiuba": { "uf": "CE", "prazo": 72 },
    "Guaraciaba do Norte": { "uf": "CE", "prazo": 48 },
    "Guaramiranga": { "uf": "CE", "prazo": 72 },
    "Hidrolandia": { "uf": "CE", "prazo": 48 },
    "Horizonte": { "uf": "CE", "prazo": 24 },
    "Ibaretama": { "uf": "CE", "prazo": 48 },
    "Ibiapina": { "uf": "CE", "prazo": 48 },
    "Ibicuitinga": { "uf": "CE", "prazo": 48 },
    "Icapui": { "uf": "CE", "prazo": 72 },
    "Ico": { "uf": "CE", "prazo": 24 },
    "Iguatu": { "uf": "CE", "prazo": 24 },
    "Independencia": { "uf": "CE", "prazo": 48 },
    "Ipaporanga": { "uf": "CE", "prazo": 24 },
    "Ipaumirim": { "uf": "CE", "prazo": 24 },
    "Ipu": { "uf": "CE", "prazo": 24 },
    "Ipueiras": { "uf": "CE", "prazo": 48 },
    "Iracema": { "uf": "CE", "prazo": 72 },
    "Irauçuba": { "uf": "CE", "prazo": 48 },
    "Itaiçaba": { "uf": "CE", "prazo": 24 },
    "Itaitinga": { "uf": "CE", "prazo": 24 },
    "Itapaje": { "uf": "CE", "prazo": 48 },
    "Itapipoca": { "uf": "CE", "prazo": 24 },
    "Itapiuna": { "uf": "CE", "prazo": 72 },
    "Itarema": { "uf": "CE", "prazo": 72 },
    "Itatira": { "uf": "CE", "prazo": 72 },
    "Jaguaretama": { "uf": "CE", "prazo": 72 },
    "Jaguaribara": { "uf": "CE", "prazo": 72 },
    "Jaguaribe": { "uf": "CE", "prazo": 24 },
    "Jaguaruana": { "uf": "CE", "prazo": 24 },
    "Jardim": { "uf": "CE", "prazo": 24 },
    "Jati": { "uf": "CE", "prazo": 48 },
    "Jijoca de Jericoacoara": { "uf": "CE", "prazo": 72 },
    "Juazeiro do Norte": { "uf": "CE", "prazo": 24 },
    "Jucas": { "uf": "CE", "prazo": 24 },
    "Lavras da Mangabeira": { "uf": "CE", "prazo": 48 },
    "Limoeiro do Norte": { "uf": "CE", "prazo": 24 },
    "Madalena": { "uf": "CE", "prazo": 48 },
    "Maracanau": { "uf": "CE", "prazo": 24 },
    "Marco": { "uf": "CE", "prazo": 72 },
    "Martinopole": { "uf": "CE", "prazo": 72 },
    "Massape": { "uf": "CE", "prazo": 72 },
    "Mauriti": { "uf": "CE", "prazo": 24 },
    "Meruoca": { "uf": "CE", "prazo": 72 },
    "Milagres": { "uf": "CE", "prazo": 24 },
    "Milha": { "uf": "CE", "prazo": 48 },
    "Miraima": { "uf": "CE", "prazo": 72 },
    "Missão Velha": { "uf": "CE", "prazo": 24 },
    "Mombaça": { "uf": "CE", "prazo": 24 },
    "Monsenhor Tabosa": { "uf": "CE", "prazo": 24 },
    "Morada Nova": { "uf": "CE", "prazo": 24 },
    "Moraujo": { "uf": "CE", "prazo": 72 },
    "Morrinhos": { "uf": "CE", "prazo": 72 },
    "Mucambo": { "uf": "CE", "prazo": 72 },
    "Mulungu": { "uf": "CE", "prazo": 72 },
    "Nova Olinda": { "uf": "CE", "prazo": 24 },
    "Nova Russas": { "uf": "CE", "prazo": 48 },
    "Novo Oriente": { "uf": "CE", "prazo": 24 },
    "Ocara": { "uf": "CE", "prazo": 48 },
    "Oros": { "uf": "CE", "prazo": 48 },
    "Pacajus": { "uf": "CE", "prazo": 24 },
    "Pacoti": { "uf": "CE", "prazo": 72 },
    "Pacuja": { "uf": "CE", "prazo": 72 },
    "Palhano": { "uf": "CE", "prazo": 24 },
    "Palmacia": { "uf": "CE", "prazo": 72 },
    "Paracuru": { "uf": "CE", "prazo": 48 },
    "Paraipaba": { "uf": "CE", "prazo": 48 },
    "Parambu": { "uf": "CE", "prazo": 24 },
    "Paramoti": { "uf": "CE", "prazo": 72 },
    "Pedra Branca": { "uf": "CE", "prazo": 48 },
    "Penaforte": { "uf": "CE", "prazo": 24 },
    "Pentecoste": { "uf": "CE", "prazo": 48 },
    "Pereiro": { "uf": "CE", "prazo": 72 },
    "Pindoretama": { "uf": "CE", "prazo": 24 },
    "Piquet Carneiro": { "uf": "CE", "prazo": 48 },
    "Pires Ferreira": { "uf": "CE", "prazo": 48 },
    "Poranga": { "uf": "CE", "prazo": 24 },
    "Porteiras": { "uf": "CE", "prazo": 24 },
    "Potengi": { "uf": "CE", "prazo": 48 },
    "Potiretama": { "uf": "CE", "prazo": 72 },
    "Quiterianópolis": { "uf": "CE", "prazo": 24 },
    "Quixada": { "uf": "CE", "prazo": 24 },
    "Quixelo": { "uf": "CE", "prazo": 48 },
    "Quixeramobim": { "uf": "CE", "prazo": 24 },
    "Quixere": { "uf": "CE", "prazo": 48 },
    "Redenção": { "uf": "CE", "prazo": 24 },
    "Reriutaba": { "uf": "CE", "prazo": 48 },
    "Russas": { "uf": "CE", "prazo": 24 },
    "Saboeiro": { "uf": "CE", "prazo": 48 },
    "Salitre": { "uf": "CE", "prazo": 24 },
    "Santa Quiteria": { "uf": "CE", "prazo": 24 },
    "Santana do Acarau": { "uf": "CE", "prazo": 72 },
    "Santana do Cariri": { "uf": "CE", "prazo": 24 },
    "São Benedito": { "uf": "CE", "prazo": 48 },
    "São Gonçalo do Amarante": { "uf": "CE", "prazo": 48 },
    "São João do Jaguaribe": { "uf": "CE", "prazo": 24 },
    "São Luis do Curu": { "uf": "CE", "prazo": 72 },
    "Senador Pompeu": { "uf": "CE", "prazo": 24 },
    "Senador Sa": { "uf": "CE", "prazo": 72 },
    "Sobral": { "uf": "CE", "prazo": 24 },
    "Solonopole": { "uf": "CE", "prazo": 24 },
    "Tabuleiro do Norte": { "uf": "CE", "prazo": 24 },
    "Tamboril": { "uf": "CE", "prazo": 24 },
    "Tarrafas": { "uf": "CE", "prazo": 48 },
    "Taua": { "uf": "CE", "prazo": 24 },
    "Tejuçuoca": { "uf": "CE", "prazo": 48 },
    "Tiangua": { "uf": "CE", "prazo": 24 },
    "Trairi": { "uf": "CE", "prazo": 48 },
    "Tururu": { "uf": "CE", "prazo": 72 },
    "Ubajara": { "uf": "CE", "prazo": 48 },
    "Umari": { "uf": "CE", "prazo": 24 },
    "Umirim": { "uf": "CE", "prazo": 72 },
    "Uruburetama": { "uf": "CE", "prazo": 72 },
    "Uruoca": { "uf": "CE", "prazo": 72 },
    "Varjota": { "uf": "CE", "prazo": 48 },
    "Varzea Alegre": { "uf": "CE", "prazo": 24 },
    "Viçosa do Ceara": { "uf": "CE", "prazo": 48 }
      }
    },

    {
      "nome": "Ceará Transportes",
      "valorPorKg": 0.50,
      "valorPorNF": 0.0015,
      "taxaColeta": 0,
      "freteMinimo": 60.00,
      "prazos": {
        "Abaiara": 72,
        "Acarape": 24,
        "Acopiara": 24,
        "Aiuaba": "Semanal",
        "Altaneira": 72,
        "Alto Santo": 24,
        "Antonina do Norte": 24,
        "Aquiraz": 24,
        "Aracati": 24,
        "Ararenda": 72,
        "Araripe": 72,
        "Arneiroz": 24,
        "Assare": 24,
        "Aurora": 24,
        "Baixio": 24,
        "Barbalha": 24,
        "Barreira": 24,
        "Barro": 24,
        "Beberibe": 24,
        "Brejo Santo": 24,
        "Campos Sales": 24,
        "Caririaçu": 24,
        "Cariús": 24,
        "Cascavel": 24,
        "Catarina": 24,
        "Catunda": 24,
        "Cedro": 24,
        "Chorozinho": 24,
        "Crateus": 24,
        "Crato": 24,
        "Erere": 24,
        "Farias Brito": 24,
        "Fortim": 24,
        "Granjeiro": 72,
        "Guaiuba": 24,
        "Horizonte": 24,
        "Icapui": "Semanal",
        "Ico": 24,
        "Iguatu": 24,
        "Independencia": 24,
        "Ipaporanga": 24,
        "Ipaumirim": 24,
        "Iracema": 24,
        "Itaiçaba": 24,
        "Itaitinga": 24,
        "Jaguaribara": 24,
        "Jaguaribe": 24,
        "Jaguaruana": 24,
        "Jardim": 72,
        "Jati": 72,
        "Juazeiro do Norte": 24,
        "Jucas": 24,
        "Lavras da Mangabeira": 24,
        "Limoeiro do Norte": 24,
        "Maranhão": 96,
        "Mauriti": 24,
        "Milagres": 24,
        "Missão Velha": 24,
        "Mombaça": 24,
        "Monsenhor Tabosa": 72,
        "Morada Nova": 24,
        "Nova Olinda": 72,
        "Nova Russas": 24,
        "Novo Oriente": 24,
        "Ocara": 24,
        "Oros": 24,
        "Pacajus": 24,
        "Pacatuba": 24,
        "Palhano": 24,
        "Paraiba": 96,
        "Parambu": 24,
        "Penaforte": 24,
        "Pereiro": 72,
        "Pindoretama": 24,
        "Poranga": 24,
        "Porteiras": 24,
        "Potengi": 72,
        "Potiretama": 24,
        "Quiterianopolis": 24,
        "Quixelo": 24,
        "Quixere": 24,
        "Russas": 24,
        "Saboeiro": "Semanal",
        "Salitre": 24,
        "Santana do Cariri": 24,
        "São João do Jaguaribe": 24,
        "Tabuleiro do Norte": 24,
        "Tamboril": 72,
        "Tarrafas": 24,
        "Taua": 24,
        "Umari": 24,
        "Varzea Alegre": 24
      }
    },

    {
      "nome": "Ceará Transportes",
      "valorPorKg": 0.85,
      "valorPorNF": 0.005,
      "taxaColeta": 25.00,
      "freteMinimo": 140.00,
      "prazos": {
        "Acaua": 96,
        "Agricolandia": 96,
        "Agua Branca": 96,
        "Alagoinha do Piaui": 96,
        "Alegrete do Piaui": 96,
        "Alto Longa": 96,
        "Altos": 96,
        "Alvorada do Gurgueia": 96,
        "Amarante": 96,
        "Angical do Piaui": 96,
        "Anisio de Abreu": 96,
        "Antonio Almeida": 96,
        "Aroazes": 96,
        "Aroeiras do Itaim": 96,
        "Arraial": 96,
        "Assuncao do Piaui": 96,
        "Avelino Lopes": 96,
        "Baixa Grande do Ribeiro": 96,
        "Barra D'Alcantara": 96,
        "Barras": 96,
        "Barreiras do Piaui": 96,
        "Barro Duro": 96,
        "Batalha": 96,
        "Bela Vista do Piaui": 96,
        "Belem do Piaui": 96,
        "Beneditinos": 96,
        "Bertolinia": 96,
        "Betania do Piaui": 96,
        "Boa Hora": 96,
        "Bocaina": 96,
        "Bom Jesus": 96,
        "Bom Principio do Piaui": 96,
        "Bonfim do Piaui": 96,
        "Boqueirao do Piaui": 96,
        "Brasileira": 96,
        "Brejo do Piaui": 96,
        "Buriti dos Lopes": 96,
        "Buriti dos Montes": 96,
        "Cabeceiras do Piaui": 96,
        "Cajazeiras do Piaui": 96,
        "Cajueiro da Praia": 96,
        "Caldeirao Grande do Piaui": 96,
        "Campinas do Piaui": 96,
        "Campo Alegre do Fidalgo": 96,
        "Campo Grande do Piaui": 96,
        "Campo Largo do Piaui": 96,
        "Campo Maior": 96,
        "Canavieira": 96,
        "Canto do Buriti": 96,
        "Capitao de Campos": 0,
        "Capitao Gervasio Oliveira": 0,
        "Caracol": 0,
        "Caridade do Piaui": 0,
        "Castelo do Piaui": 0,
        "Caxingo": 0,
        "Cocal": 0,
        "Cocal de Telha": 0,
        "Cocal dos Alves": 0,
        "Coivaras": 0,
        "Colonia do Gurgueia": 0,
        "Colonia do Piaui": 0,
        "Conceicao do Caninde": 0,
        "Coronel Jose Dias": 0,
        "Corrente": 0,
        "Cristalandia do Piaui": 0,
        "Cristino Castro": 0,
        "Curimata": 0,
        "Currais": 0,
        "Curral Novo do Piaui": 0,
        "Curralinhos": 0,
        "Demerval Lobao": 0,
        "Dirceu Arcoverde": 0,
        "Dom Expedito Lopes": 0,
        "Dom Inocencio": 0,
        "Domingos Mourao": 0,
        "Elesbao Veloso": 0,
        "Eliseu Martins": 0,
        "Esperantina": 0,
        "Fartura do Piaui": 0,
        "Flores do Piaui": 0,
        "Floresta do Piaui": 0,
        "Floriano": 0,
        "Francinopolis": 0,
        "Francisco Ayres": 0,
        "Francisco Macedo": 0,
        "Francisco Santos": 0,
        "Fronteiras": 0,
        "Geminiano": 0,
        "Gilbues": 0,
        "Guadalupe": 0,
        "Guaribas": 0,
        "Hugo Napoleao": 0,
        "Ilha Grande": 0,
        "Inhuma": 0,
        "Ipiranga do Piaui": 0,
        "Isaias Coelho": 0,
        "Itainopolis": 0,
        "Itaueira": 0,
        "Jacobina do Piaui": 0,
        "Jaicos": 0,
        "Jardim do Mulato": 0,
        "Jatoba do Piaui": 0,
        "Jerumenha": 0,
        "Joao Costa": 0,
        "Joaquim Pires": 0,
        "Joca Marques": 0,
        "Jose de Freitas": 0,
        "Juazeiro do Piaui": 0,
        "Julio Borges": 0,
        "Jurema": 0,
        "Lagoa Alegre": 0,
        "Lagoa de Sao Francisco": 0,
        "Lagoa do Barro do Piaui": 0,
        "Lagoa do Piaui": 0,
        "Lagoa do Sitio": 0,
        "Lagoinha do Piaui": 0,
        "Landri Sales": 0,
        "Luis Correia": 0,
        "Luzilandia": 0,
        "Madeiro": 0,
        "Manoel Emidio": 0,
        "Marcolandia": 0,
        "Marcos Parente": 0,
        "Massape do Piaui": 0,
        "Matias Olimpio": 0,
        "Miguel Alves": 0,
        "Miguel Leao": 0,
        "Milton Brandao": 0,
        "Monsenhor Gil": 0,
        "Monsenhor Hipolito": 0,
        "Monte Alegre do Piaui": 0,
        "Morro Cabeca no Tempo": 0,
        "Morro do Chapeu do Piaui": 0,
        "Murici dos Portelas": 0,
        "Nazare do Piaui": 0,
        "Nossa Senhora de Nazare": 0,
        "Nossa Senhora dos Remedios": 0,
        "Nova Santa Rita": 0,
        "Novo Oriente do Piaui": 0,
        "Novo Santo Antonio": 0,
        "Oeiras": 0,
        "Olho D'Agua do Piaui": 0,
        "Padre Marcos": 0,
        "Paes Landim": 0,
        "Pajeu do Piaui": 0,
        "Palmeira do Piaui": 0,
        "Palmeirais": 0,
        "Paqueta": 0,
        "Parnagua": 0,
        "Parnaiba": 0,
        "Passagem Franca do Piaui": 0,
        "Patos do Piaui": 0,
        "Paulistana": 0,
        "Pavussu": 0,
        "Pedro II": 0,
        "Pedro Laurentino": 0,
        "Picos": 0,
        "Pimenteiras": 0,
        "Pio IX": 0,
        "Piracuruca": 0,
        "Piripiri": 0,
        "Porto": 0,
        "Porto Alegre do Piaui": 0,
        "Prata do Piaui": 0,
        "Queimada Nova": 0,
        "Redencao do Gurgueia": 0,
        "Regeneracao": 0,
        "Riacho Frio": 0,
        "Ribeira do Piaui": 0,
        "Ribeiro Goncalves": 0,
        "Rio Grande do Piaui": 0,
        "Santa Cruz do Piaui": 0,
        "Santa Cruz dos Milagres": 0,
        "Santa Filomena": 0,
        "Santa Luz": 0,
        "Santa Rosa do Piaui": 0,
        "Santana do Piaui": 0,
        "Santo Antonio de Lisboa": 0,
        "Santo Antonio dos Milagres": 0,
        "Santo Inacio do Piaui": 0,
        "Sao Braz do Piaui": 0,
        "Sao Felix do Piaui": 0,
        "Sao Francisco de Assis do Piaui": 0,
        "Sao Francisco do Piaui": 0,
        "Sao Goncalo do Gurgueia": 0,
        "Sao Goncalo do Piaui": 0,
        "Sao Joao da Canabrava": 0,
        "Sao Joao da Fronteira": 0,
        "Sao Joao da Serra": 0,
        "Sao Joao da Varjota": 0,
        "Sao Joao do Arraial": 0,
        "Sao Joao do Piaui": 0,
        "Sao Jose do Divino": 0,
        "Sao Jose do Peixe": 0,
        "Sao Jose do Piaui": 0,
        "Sao Juliao": 0,
        "Sao Lourenco do Piaui": 0,
        "Sao Luis do Piaui": 0,
        "Sao Miguel da Baixa Grande": 0,
        "Sao Miguel do Fidalgo": 0,
        "Sao Miguel do Tapuio": 0,
        "Sao Pedro do Piaui": 0,
        "Sao Raimundo Nonato": 0,
        "Sebastiao Barros": 0,
        "Sebastiao Leal": 0,
        "Sigefredo Pacheco": 0,
        "Simoes": 0,
        "Simplicio Mendes": 0,
        "Socorro do Piaui": 0,
        "Sussuapara": 0,
        "Tamboril do Piaui": 0,
        "Tanque do Piaui": 0,
        "Teresina": 0,
        "Uniao": 0,
        "Urucui": 0,
        "Valenca do Piaui": 96,
        "Varzea Branca": 96,
        "Varzea Grande": 96,
        "Vera Mendes": 96,
        "Vila Nova do Piaui": 96,
        "Wall Ferraz": 96
      }
    },

    {
      "nome": "Potyguar",
      "valorPorKg": 6.0,
      "valorPorNF": 11.0,
      "taxaColeta": 0.01,
      "freteMinimo": 100.00,
      "prazos": {
        "Mossoro": 48,
        "Natal": 48,
        "Rio Grande do Norte": 96
      }
    },

    {
      "nome": "Transportadora D",
      "valorPorKg": 4.8,
      "valorPorNF": 9.0,
      "taxaColeta": 3.0,
      "freteMinimo": 50.00,
      "prazos": {
        "Fortaleza": 24,
        "Maracanau": 24,
        "Caucaia": 24
      }
    }
  ]
};






