  window.DADOS_FRETE = {
  "transportadoras": [
    {
      "nome": "Cbirdex",
      "valorPorKg": 0.45,
      "valorPorNF": 0.005,
      "taxaColeta": 0,
      "freteMinimo": 60.00,
      "prazos": {
        "Abaiara": 24 | 60000000 a 61000000,
        "Acarape": 24,
        "Acarau": 72,
        "Acopiara": 24,
        "Aiuaba": 48,
        "Alcantaras": 72,
        "Altaneira": 48,
        "Alto Santo": 72,
        "Amontada": 72,
        "Antonina do Norte": 48,
        "Apuiares": 48,
        "Aquiraz": 24,
        "Aracati": 24,
        "Aracoiaba": 72,
        "Ararenda": 24,
        "Araripe": 24,
        "Aratuba": 72,
        "Arneiroz": 48,
        "Assare": 24,
        "Aurora": 24,
        "Baixio": 24,
        "Banabuiu": 48,
        "Barbalha": 24,
        "Barreira": 72,
        "Barro": 48,
        "Barroquinha": 72,
        "Baturite": 24,
        "Beberibe": 24,
        "Bela Cruz": 72,
        "Boa Viagem": 48,
        "Brejo Santo": 24,
        "Camocim": 72,
        "Campos Sales": 24,
        "Caninde": 24,
        "Capistrano": 72,
        "Caridade": 72,
        "Carire": 72,
        "Caririaçu": 24,
        "Carius": 48,
        "Carnaubal": 72,
        "Cascavel": 24,
        "Catarina": 48,
        "Catunda": 24,
        "Caucaia": 24,
        "Cedro": 48,
        "Chaval": 72,
        "Choro": 48,
        "Chorozinho": 72,
        "Coreau": 72,
        "Crateus": 24,
        "Crato": 24,
        "Croata": 24,
        "Cruz": 72,
        "Deputado Irapuan Pinheiro": 48,
        "Erere": 72,
        "Eusebio": 24,
        "Farias Brito": 24,
        "Forquilha": 48,
        "Fortim": 48,
        "Frecheirinha": 24,
        "General Sampaio": 48,
        "Graça": 72,
        "Granja": 72,
        "Granjeiro": 72,
        "Groairas": 72,
        "Guaiuba": 72,
        "Guaraciaba do Norte": 48,
        "Guaramiranga": 72,
        "Hidrolandia": 48,
        "Horizonte": 24,
        "Ibaretama": 48,
        "Ibiapina": 48,
        "Ibicuitinga": 48,
        "Icapui": 72,
        "Ico": 24,
        "Iguatu": 24,
        "Independencia": 48,
        "Ipaporanga": 24,
        "Ipaumirim": 24,
        "Ipu": 24,
        "Ipueiras": 48,
        "Iracema": 72,
        "Irauçuba": 48,
        "Itaiçaba": 24,
        "Itaitinga": 24,
        "Itapaje": 48,
        "Itapipoca": 24,
        "Itapiuna": 72,
        "Itarema": 72,
        "Itatira": 72,
        "Jaguaretama": 72,
        "Jaguaribara": 72,
        "Jaguaribe": 24,
        "Jaguaruana": 24,
        "Jardim": 24,
        "Jati": 48,
        "Jijoca de Jericoacoara": 72,
        "Juazeiro do Norte": 24,
        "Jucas": 24,
        "Lavras da Mangabeira": 48,
        "Limoeiro do Norte": 24,
        "Madalena": 48,
        "Maracanau": 24,
        "Marco": 72,
        "Martinopole": 72,
        "Massape": 72,
        "Mauriti": 24,
        "Meruoca": 72,
        "Milagres": 24,
        "Milha": 48,
        "Miraima": 72,
        "Missão Velha": 24,
        "Mombaça": 24,
        "Monsenhor Tabosa": 24,
        "Morada Nova": 24,
        "Moraujo": 72,
        "Morrinhos": 72,
        "Mucambo": 72,
        "Mulungu": 72,
        "Nova Olinda": 24,
        "Nova Russas": 48,
        "Novo Oriente": 24,
        "Ocara": 48,
        "Oros": 48,
        "Pacajus": 24,
        "Pacoti": 72,
        "Pacuja": 72,
        "Palhano": 24,
        "Palmacia": 72,
        "Paracuru": 48,
        "Paraipaba": 48,
        "Parambu": 24,
        "Paramoti": 72,
        "Pedra Branca": 48,
        "Penaforte": 24,
        "Pentecoste": 48,
        "Pereiro": 72,
        "Pindoretama": 24,
        "Piquet Carneiro": 48,
        "Pires Ferreira": 48,
        "Poranga": 24,
        "Porteiras": 24,
        "Potengi": 48,
        "Potiretama": 72,
        "Quiterianópolis": 24,
        "Quixada": 24,
        "Quixelo": 48,
        "Quixeramobim": 24,
        "Quixere": 48,
        "Redenção": 24,
        "Reriutaba": 48,
        "Russas": 24,
        "Saboeiro": 48,
        "Salitre": 24,
        "Santa Quiteria": 24,
        "Santana do Acarau": 72,
        "Santana do Cariri": 24,
        "São Benedito": 48,
        "São Gonçalo do Amarante": 48,
        "São João do Jaguaribe": 24,
        "São Luis do Curu": 72,
        "Senador Pompeu": 24,
        "Senador Sa": 72,
        "Sobral": 24,
        "Solonopole": 24,
        "Tabuleiro do Norte": 24,
        "Tamboril": 24,
        "Tarrafas": 48,
        "Taua": 24,
        "Tejuçuoca": 48,
        "Tiangua": 24,
        "Trairi": 48,
        "Tururu": 72,
        "Ubajara": 48,
        "Umari": 24,
        "Umirim": 72,
        "Uruburetama": 72,
        "Uruoca": 72,
        "Varjota": 48,
        "Varzea Alegre": 24,
        "Viçosa do Ceara": 48
      }
    },

    {
      "nome": "Ceará Transportes",
      "valorPorKg": 0.50,
      "valorPorNF": 0.0015,
      "taxaColeta": 0,
      "freteMinimo": 60.00,
      "prazos": {
        "Abaiara": 72,
        "Acarape": 24,
        "Acopiara": 24,
        "Aiuaba": "Semanal",
        "Altaneira": 72,
        "Alto Santo": 24,
        "Antonina do Norte": 24,
        "Aquiraz": 24,
        "Aracati": 24,
        "Ararenda": 72,
        "Araripe": 72,
        "Arneiroz": 24,
        "Assare": 24,
        "Aurora": 24,
        "Baixio": 24,
        "Barbalha": 24,
        "Barreira": 24,
        "Barro": 24,
        "Beberibe": 24,
        "Brejo Santo": 24,
        "Campos Sales": 24,
        "Caririaçu": 24,
        "Cariús": 24,
        "Cascavel": 24,
        "Catarina": 24,
        "Catunda": 24,
        "Cedro": 24,
        "Chorozinho": 24,
        "Crateus": 24,
        "Crato": 24,
        "Erere": 24,
        "Farias Brito": 24,
        "Fortim": 24,
        "Granjeiro": 72,
        "Guaiuba": 24,
        "Horizonte": 24,
        "Icapui": "Semanal",
        "Ico": 24,
        "Iguatu": 24,
        "Independencia": 24,
        "Ipaporanga": 24,
        "Ipaumirim": 24,
        "Iracema": 24,
        "Itaiçaba": 24,
        "Itaitinga": 24,
        "Jaguaribara": 24,
        "Jaguaribe": 24,
        "Jaguaruana": 24,
        "Jardim": 72,
        "Jati": 72,
        "Juazeiro do Norte": 24,
        "Jucas": 24,
        "Lavras da Mangabeira": 24,
        "Limoeiro do Norte": 24,
        "Maranhão": 96,
        "Mauriti": 24,
        "Milagres": 24,
        "Missão Velha": 24,
        "Mombaça": 24,
        "Monsenhor Tabosa": 72,
        "Morada Nova": 24,
        "Nova Olinda": 72,
        "Nova Russas": 24,
        "Novo Oriente": 24,
        "Ocara": 24,
        "Oros": 24,
        "Pacajus": 24,
        "Pacatuba": 24,
        "Palhano": 24,
        "Paraiba": 96,
        "Parambu": 24,
        "Penaforte": 24,
        "Pereiro": 72,
        "Pindoretama": 24,
        "Poranga": 24,
        "Porteiras": 24,
        "Potengi": 72,
        "Potiretama": 24,
        "Quiterianopolis": 24,
        "Quixelo": 24,
        "Quixere": 24,
        "Russas": 24,
        "Saboeiro": "Semanal",
        "Salitre": 24,
        "Santana do Cariri": 24,
        "São João do Jaguaribe": 24,
        "Tabuleiro do Norte": 24,
        "Tamboril": 72,
        "Tarrafas": 24,
        "Taua": 24,
        "Umari": 24,
        "Varzea Alegre": 24
      }
    },

    {
      "nome": "Ceará Transportes",
      "valorPorKg": 0.85,
      "valorPorNF": 0.005,
      "taxaColeta": 25.00,
      "freteMinimo": 140.00,
      "prazos": {
        "Acaua": 96,
        "Agricolandia": 96,
        "Agua Branca": 96,
        "Alagoinha do Piaui": 96,
        "Alegrete do Piaui": 96,
        "Alto Longa": 96,
        "Altos": 96,
        "Alvorada do Gurgueia": 96,
        "Amarante": 96,
        "Angical do Piaui": 96,
        "Anisio de Abreu": 96,
        "Antonio Almeida": 96,
        "Aroazes": 96,
        "Aroeiras do Itaim": 96,
        "Arraial": 96,
        "Assuncao do Piaui": 96,
        "Avelino Lopes": 96,
        "Baixa Grande do Ribeiro": 96,
        "Barra D'Alcantara": 96,
        "Barras": 96,
        "Barreiras do Piaui": 96,
        "Barro Duro": 96,
        "Batalha": 96,
        "Bela Vista do Piaui": 96,
        "Belem do Piaui": 96,
        "Beneditinos": 96,
        "Bertolinia": 96,
        "Betania do Piaui": 96,
        "Boa Hora": 96,
        "Bocaina": 96,
        "Bom Jesus": 96,
        "Bom Principio do Piaui": 96,
        "Bonfim do Piaui": 96,
        "Boqueirao do Piaui": 96,
        "Brasileira": 96,
        "Brejo do Piaui": 96,
        "Buriti dos Lopes": 96,
        "Buriti dos Montes": 96,
        "Cabeceiras do Piaui": 96,
        "Cajazeiras do Piaui": 96,
        "Cajueiro da Praia": 96,
        "Caldeirao Grande do Piaui": 96,
        "Campinas do Piaui": 96,
        "Campo Alegre do Fidalgo": 96,
        "Campo Grande do Piaui": 96,
        "Campo Largo do Piaui": 96,
        "Campo Maior": 96,
        "Canavieira": 96,
        "Canto do Buriti": 96,
        "Capitao de Campos": 0,
        "Capitao Gervasio Oliveira": 0,
        "Caracol": 0,
        "Caridade do Piaui": 0,
        "Castelo do Piaui": 0,
        "Caxingo": 0,
        "Cocal": 0,
        "Cocal de Telha": 0,
        "Cocal dos Alves": 0,
        "Coivaras": 0,
        "Colonia do Gurgueia": 0,
        "Colonia do Piaui": 0,
        "Conceicao do Caninde": 0,
        "Coronel Jose Dias": 0,
        "Corrente": 0,
        "Cristalandia do Piaui": 0,
        "Cristino Castro": 0,
        "Curimata": 0,
        "Currais": 0,
        "Curral Novo do Piaui": 0,
        "Curralinhos": 0,
        "Demerval Lobao": 0,
        "Dirceu Arcoverde": 0,
        "Dom Expedito Lopes": 0,
        "Dom Inocencio": 0,
        "Domingos Mourao": 0,
        "Elesbao Veloso": 0,
        "Eliseu Martins": 0,
        "Esperantina": 0,
        "Fartura do Piaui": 0,
        "Flores do Piaui": 0,
        "Floresta do Piaui": 0,
        "Floriano": 0,
        "Francinopolis": 0,
        "Francisco Ayres": 0,
        "Francisco Macedo": 0,
        "Francisco Santos": 0,
        "Fronteiras": 0,
        "Geminiano": 0,
        "Gilbues": 0,
        "Guadalupe": 0,
        "Guaribas": 0,
        "Hugo Napoleao": 0,
        "Ilha Grande": 0,
        "Inhuma": 0,
        "Ipiranga do Piaui": 0,
        "Isaias Coelho": 0,
        "Itainopolis": 0,
        "Itaueira": 0,
        "Jacobina do Piaui": 0,
        "Jaicos": 0,
        "Jardim do Mulato": 0,
        "Jatoba do Piaui": 0,
        "Jerumenha": 0,
        "Joao Costa": 0,
        "Joaquim Pires": 0,
        "Joca Marques": 0,
        "Jose de Freitas": 0,
        "Juazeiro do Piaui": 0,
        "Julio Borges": 0,
        "Jurema": 0,
        "Lagoa Alegre": 0,
        "Lagoa de Sao Francisco": 0,
        "Lagoa do Barro do Piaui": 0,
        "Lagoa do Piaui": 0,
        "Lagoa do Sitio": 0,
        "Lagoinha do Piaui": 0,
        "Landri Sales": 0,
        "Luis Correia": 0,
        "Luzilandia": 0,
        "Madeiro": 0,
        "Manoel Emidio": 0,
        "Marcolandia": 0,
        "Marcos Parente": 0,
        "Massape do Piaui": 0,
        "Matias Olimpio": 0,
        "Miguel Alves": 0,
        "Miguel Leao": 0,
        "Milton Brandao": 0,
        "Monsenhor Gil": 0,
        "Monsenhor Hipolito": 0,
        "Monte Alegre do Piaui": 0,
        "Morro Cabeca no Tempo": 0,
        "Morro do Chapeu do Piaui": 0,
        "Murici dos Portelas": 0,
        "Nazare do Piaui": 0,
        "Nossa Senhora de Nazare": 0,
        "Nossa Senhora dos Remedios": 0,
        "Nova Santa Rita": 0,
        "Novo Oriente do Piaui": 0,
        "Novo Santo Antonio": 0,
        "Oeiras": 0,
        "Olho D'Agua do Piaui": 0,
        "Padre Marcos": 0,
        "Paes Landim": 0,
        "Pajeu do Piaui": 0,
        "Palmeira do Piaui": 0,
        "Palmeirais": 0,
        "Paqueta": 0,
        "Parnagua": 0,
        "Parnaiba": 0,
        "Passagem Franca do Piaui": 0,
        "Patos do Piaui": 0,
        "Paulistana": 0,
        "Pavussu": 0,
        "Pedro II": 0,
        "Pedro Laurentino": 0,
        "Picos": 0,
        "Pimenteiras": 0,
        "Pio IX": 0,
        "Piracuruca": 0,
        "Piripiri": 0,
        "Porto": 0,
        "Porto Alegre do Piaui": 0,
        "Prata do Piaui": 0,
        "Queimada Nova": 0,
        "Redencao do Gurgueia": 0,
        "Regeneracao": 0,
        "Riacho Frio": 0,
        "Ribeira do Piaui": 0,
        "Ribeiro Goncalves": 0,
        "Rio Grande do Piaui": 0,
        "Santa Cruz do Piaui": 0,
        "Santa Cruz dos Milagres": 0,
        "Santa Filomena": 0,
        "Santa Luz": 0,
        "Santa Rosa do Piaui": 0,
        "Santana do Piaui": 0,
        "Santo Antonio de Lisboa": 0,
        "Santo Antonio dos Milagres": 0,
        "Santo Inacio do Piaui": 0,
        "Sao Braz do Piaui": 0,
        "Sao Felix do Piaui": 0,
        "Sao Francisco de Assis do Piaui": 0,
        "Sao Francisco do Piaui": 0,
        "Sao Goncalo do Gurgueia": 0,
        "Sao Goncalo do Piaui": 0,
        "Sao Joao da Canabrava": 0,
        "Sao Joao da Fronteira": 0,
        "Sao Joao da Serra": 0,
        "Sao Joao da Varjota": 0,
        "Sao Joao do Arraial": 0,
        "Sao Joao do Piaui": 0,
        "Sao Jose do Divino": 0,
        "Sao Jose do Peixe": 0,
        "Sao Jose do Piaui": 0,
        "Sao Juliao": 0,
        "Sao Lourenco do Piaui": 0,
        "Sao Luis do Piaui": 0,
        "Sao Miguel da Baixa Grande": 0,
        "Sao Miguel do Fidalgo": 0,
        "Sao Miguel do Tapuio": 0,
        "Sao Pedro do Piaui": 0,
        "Sao Raimundo Nonato": 0,
        "Sebastiao Barros": 0,
        "Sebastiao Leal": 0,
        "Sigefredo Pacheco": 0,
        "Simoes": 0,
        "Simplicio Mendes": 0,
        "Socorro do Piaui": 0,
        "Sussuapara": 0,
        "Tamboril do Piaui": 0,
        "Tanque do Piaui": 0,
        "Teresina": 0,
        "Uniao": 0,
        "Urucui": 0,
        "Valenca do Piaui": 96,
        "Varzea Branca": 96,
        "Varzea Grande": 96,
        "Vera Mendes": 96,
        "Vila Nova do Piaui": 96,
        "Wall Ferraz": 96
      }
    },

    {
      "nome": "Potyguar",
      "valorPorKg": 6.0,
      "valorPorNF": 11.0,
      "taxaColeta": 0.01,
      "freteMinimo": 100.00,
      "prazos": {
        "Mossoro": 48,
        "Natal": 48,
        "Rio Grande do Norte": 96
      }
    },

    {
      "nome": "Transportadora D",
      "valorPorKg": 4.8,
      "valorPorNF": 9.0,
      "taxaColeta": 3.0,
      "freteMinimo": 50.00,
      "prazos": {
        "Fortaleza": 24,
        "Maracanau": 24,
        "Caucaia": 24
      }
    }
  ]
};



